num1=float(input("enter the first number"))
num2=float(input("enter the second number"))
print("sum=",num1+num2)
print("difference =",num1-num2)
print("product =",num1*num2)
print("divide =",num1/num2)