a=int(input('enter the marks of 1st subject'))
b=int(input('enter the marks of 2nd subject'))
c=int(input('enter the marks of 3rd subject'))
d=int(input('enter the marks of 4th subject'))
e=int(input('enter the marks of 5th subject'))
total_sub=(5)
total_marks=(a+b+c+d+e)
average=(total_marks/total_sub)
print("total marks",total_marks)
print("average marks",average)